include:
  template: Security/License-Management.gitlab-ci.yml

.test: &test
  script:
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized (tmpdir)...."
  - TEST_DAEMONIZE=tmpdir make acceptance
  - echo "Running just the acceptance tests daemonized (inplace)...."
  - TEST_DAEMONIZE=inplace make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages

license_management:
  variables:
    SETUP_CMD: echo "Skip setup. Dependency already vendored"

code_quality:
  image: docker:19.03-git
  services:
    - docker:19.03-dind
  variables:
    DOCKER_DRIVER: overlay2
    CODECLIMATE_FORMAT: json
  dependencies: []
  script:
    - ./scripts/codequality analyze -f json --dev | tee gl-code-quality-report.json
  artifacts:
    paths: [gl-code-quality-report.json]
    expire_in: 7d

verify:
  image: golang:1.11
  script:
    - make setup
    - make verify
    - make cover
  artifacts:
    paths:
      - coverage.html

test:1.11:
  image: golang:1.11
  <<: *test

test:1.12:
  image: golang:1.12
  <<: *test
