image: golang:1.8

.test: &test
  script:
  - make setup
  - make verify
  - make cover
  - make test
  artifacts:
    paths:
      - bin/gitlab-pages
      - coverage.html

test:1.8:
  <<: *test
  
test:1.9:
  image: golang:1.9
  <<: *test
