include:
  template: License-Management.gitlab-ci.yml

variables:
  GO111MODULE: "on"

.test: &test
  script:
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized (tmpdir)...."
  - TEST_DAEMONIZE=tmpdir make acceptance
  - echo "Running just the acceptance tests daemonized (inplace)...."
  - TEST_DAEMONIZE=inplace make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages

verify:
  image: golang:1.11
  script:
    - make setup
    - make verify
    - make cover
  artifacts:
    paths:
      - coverage.html

test:1.11:
  image: golang:1.11
  <<: *test

test:1.12:
  image: golang:1.12
  <<: *test
