include:
  template: License-Management.gitlab-ci.yml
  variable:
    - LICENSE_MANAGEMENT_SETUP_CMD: "go get"

.test: &test
  script:
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized (tmpdir)...."
  - TEST_DAEMONIZE=tmpdir make acceptance
  - echo "Running just the acceptance tests daemonized (inplace)...."
  - TEST_DAEMONIZE=inplace make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages

license_management:
  variables:
    SETUP_CMD: echo "Skip setup. Dependency already vendored"

verify:
  image: golang:1.11
  script:
    - make setup
    - make verify
    - make cover
  artifacts:
    paths:
      - coverage.html

test:1.8:
  image: golang:1.8
  <<: *test

test:1.9:
  image: golang:1.9
  <<: *test

test:1.10:
  image: golang:1.10
  <<: *test

test:1.11:
  image: golang:1.11
  <<: *test
