image: golang:1.8

.test: &test
  script:
  - make setup
  - make verify
  - make cover
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized...."
  - TEST_DAEMONIZE=1 make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages
      - coverage.html

test:1.8:
  <<: *test

test:1.9:
  image: golang:1.9
  <<: *test

test:1.10:
  image: golang:1.10
  <<: *test
