include:
  - template: Security/License-Management.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

.test: &test
  script:
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized (tmpdir)...."
  - TEST_DAEMONIZE=tmpdir make acceptance
  - echo "Running just the acceptance tests daemonized (inplace)...."
  - TEST_DAEMONIZE=inplace make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages

license_management:
  variables:
    SETUP_CMD: echo "Skip setup. Dependency already vendored"

verify:
  image: golang:1.11
  script:
    - make setup
    - make verify
    - make cover
  artifacts:
    paths:
      - coverage.html
      
sast:
  before_script: 
    - make setup

test:1.11:
  image: golang:1.11
  <<: *test

test:1.12:
  image: golang:1.12
  <<: *test
