include:
  template: Security/License-Management.gitlab-ci.yml

.go-mod-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.GOPATH
  before_script:
    - mkdir -p .GOPATH
  cache:
    paths:
      - .GOPATH/pkg/mod/

.tests:
  extends: .go-mod-cache
  script:
  - echo "Running all tests without daemonizing..."
  - make test
  - echo "Running just the acceptance tests daemonized (tmpdir)...."
  - TEST_DAEMONIZE=tmpdir make acceptance
  - echo "Running just the acceptance tests daemonized (inplace)...."
  - TEST_DAEMONIZE=inplace make acceptance
  artifacts:
    paths:
      - bin/gitlab-pages

license_management:
  variables:
    LICENSE_MANAGEMENT_SETUP_CMD: go mod vendor

verify:
  extends: .go-mod-cache
  image: golang:1.11
  script:
    - make setup
    - make verify
    - make cover
  artifacts:
    paths:
      - coverage.html

test:1.11:
  extends: .tests
  image: golang:1.11

test:1.12:
  extends: .tests
  image: golang:1.12

test:1.13:
  extends: .tests
  image: golang:1.13
